### ISSUE TITLE
fail to update assertscan

### ISSUE THREAD

**Issue by serfend** [TeraSecTeam/ary#1]
```bash
./ary --assertscan --engine all --update -v
```

```plaintext
erfend@kali:~/桌面/tary$ ./ary --assertscan --engine all --update -v

 ______     ______     __  __    
/\  __ \   /\  == \   /\ \_\ \   
\ \  __ \  \ \  __<   \ \____ \  
 \ \_\ \_\  \ \_\ \_\  \/\_____\ 
  \/_/\/_/   \/_/ /_/   \/_____/ 
                                 

version : 2。0。0 PUBLIC
author : Ali0th / github.com/Martin2877 / martin2877@foxmail.com
descript: 
This is a tool to use many other tools. 

Statement: 
This tool is only for learning and testing. It is strictly prohibited to use for illegal purposes. The developer shall not be responsible for the illegal acts of the users.

Traceback (most recent call last):
  File "ary.py", line 199, in <module>
  File "ary.py", line 137, in command
  File "modules/assertscan.py", line 220, in update
AttributeError: 'ARL' object has no attribute 'update'
[10727] Failed to execute script ary


```

**Comment by Martin2877** [comment]
小bug , 不影响实际流程，下版本会修复此问题。
